{{- $fullname := include "zookeeper.fullname" . -}}
{{- $name := include "zookeeper.name" . -}}
{{- $chart := include "zookeeper.chart" . -}}
{{- $root := . }}
{{ range .Values.nodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ .id }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $root.Release.Name }}
      server: {{ $fullname }}-{{ .id }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $root.Release.Name }}
        server: {{ $fullname }}-{{ .id }}
    spec:
      {{- if $root.Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ $root.Values.image.pullSecrets }}
      {{- end}}
      containers:
        - name: {{ $root.Chart.Name }}
          image: "{{ $root.Values.image.registry }}{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: leader
              containerPort: 3888
              protocol: TCP
            - name: peer
              containerPort: 2888
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - mountPath: /var/datalog
              subPath: zookeeper/datalog
              name: zookeeper-data
            - mountPath: /var/data
              subPath: zookeeper/data
              name: zookeeper-data
            {{- if $root.Values.secrets.password }}
            - mountPath: "/etc/zookeeper_jaas.conf"
              subPath: jaasconfig
              name: zookeeper-jaas-config
              readOnly: true
            {{- end}}
          env:
            - name: ZOO_MY_ID
              value: "{{ .id }}"
            - name: ZOO_SERVERS
              value: "server.1={{ if eq .id "1" }}{{ "0.0.0.0" }}{{ else }}{{ $fullname }}-1{{ end }}:2888:3888 server.2={{ if eq .id "2" }}{{ "0.0.0.0" }}{{ else }}{{ $fullname }}-2{{ end }}:2888:3888 server.3={{ if eq .id "3" }}{{ "0.0.0.0" }}{{ else }}{{ $fullname }}-3{{ end }}:2888:3888"
            - name: ZOO_DATA_LOG_DIR
              value: "/var/datalog"
            - name: ZOO_DATA_DIR
              value: "/var/data"
            - name: JVMFLAGS
              value: "{{ $root.Values.environment.jvmFlags }}"
            {{- if $root.Values.secrets.password }}
            - name: ZOO_ENABLE_QUORUM_SASL
              value: "false"
            - name: ZOO_ENABLE_CLIENT_SASL
              value: "false"
            - name: JAAS_CONFIG_LOCATION
              value: "/etc/zookeeper_jaas.conf"
            {{- end}}
          resources:
{{ toYaml $root.Values.resources | indent 12 }}
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: {{ $fullname }}-{{ .id }}
        {{- if $root.Values.secrets.password }}
        - name: zookeeper-jaas-config
          secret:
            secretName: {{ $fullname }}-jaas-config
        {{- end}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- if .zone }}
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - {{ .zone }}
            {{- end}}
            {{- if .hostname }}
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - {{ .hostname }}
            {{- end}}
{{ end }}
