{{- $fullname := include "zookeeper.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-jaas-config
type: Opaque
stringData:
  jaasconfig: |
    QuorumServer {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        user_zookeeper="{{ .Values.secrets.password }}";
    };
    QuorumLearner {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        username="zookeeper"
        password="{{ .Values.secrets.password }}";
    };
    Server {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        user_kafka="{{ .Values.secrets.password }}";
    };
