{{- $fullname := include "zookeeper.fullname" . -}}
{{- $name := include "zookeeper.name" . -}}
{{- $root := . }}
{{ range .Values.nodes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullname }}-k8s{{ . }}
  labels:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
    node: k8s{{ . }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: /var/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s{{ . }}
    {{ end }}
