# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: flink
  tag: 1.15.0-scala_2.12-java11
  pullPolicy: Always
  pullSecrets:

jobmanager:
  resources:
    limits:
     cpu: 500m
     memory: 320Mi
    requests:
     cpu: 100m
     memory: 320Mi
  environment:
    - name: FLINK_PROPERTIES
      value: |
        heartbeat.timeout: 90000
        heartbeat.interval: 15000
        jobmanager.heap.size: 256m
        # state.backend.fs.checkpointdir: s3a://flink/backend/checkpoints
        # state.checkpoints.dir: s3a://flink/checkpoints
        # state.savepoints.dir: s3a://flink/savepoints
        # fs.hdfs.hdfssite: /core-site.xml
        metrics.reporters: prometheus
        metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prometheus.port: 9090
        # high-availability: kubernetes
        # kubernetes.cluster-id: cluster1
        # high-availability.storageDir: s3://flink/recovery
  storage:
    size: 4Gi
    storageClass: hostpath-csi

taskmanager:
  replicas: 2
  taskslots: 1
  resources:
    limits:
     cpu: 500m
     memory: 1200Mi
    requests:
     cpu: 100m
     memory: 1200Mi
  environment:
    - name: FLINK_PROPERTIES
      value: |
        heartbeat.timeout: 90000
        heartbeat.interval: 15000
        taskmanager.memory.process.size: 1024m
        taskmanager.memory.network.fraction: 0.1
        taskmanager.memory.managed.fraction: 0.1
        # state.backend.fs.checkpointdir: s3a://flink/backend/checkpoints
        # state.checkpoints.dir: s3a://flink/checkpoints
        # state.savepoints.dir: s3a://flink/savepoints
        # fs.hdfs.hdfssite: /core-site.xml
        metrics.reporters: prometheus
        metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prometheus.port: 9090
  storage:
    size: 8Gi
    storageClass: hostpath-csi
