{{- $fullname := include "kafka.fullname" . -}}
{{- if .Values.secrets.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-jaas-config
type: Opaque
stringData:
  jaasconfig: |
    Client {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        username="kafka"
        password="{{ .Values.secrets.password }}";
    };
{{- end}}
