global:
  storageClass: hostpath-csi

kafka:
  image:
    pullPolicy: IfNotPresent
  replicaCount: 3
  heapOpts: "-Xmx1024m -Xms1024m"
  resources:
    limits:
     cpu: 500m
     memory: 1200Mi
    requests:
     cpu: 100m
     memory: 1200Mi
  # updateStrategy:
  #   type: OnDelete
  podAntiAffinityPreset: hard
  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: true
  zookeeper:
    enabled: true
    image:
      pullPolicy: IfNotPresent
    replicaCount: 3
    heapSize: 512
    resources:
      limits:
       cpu: 500m
       memory: 700Mi
      requests:
       cpu: 100m
       memory: 700Mi
    # updateStrategy:
    #   type: OnDelete
    podAntiAffinityPreset: hard
    metrics:
      enabled: true
