apiVersion: v1
appVersion: 2022.6.25
description: A Helm chart for installing Minio
name: minio
version: 1.0.0
dependencies:
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
