apiVersion: v1
appVersion: 14.4.0
description: A Helm chart for installing PostgreSQL
name: postgresql
version: 1.0.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
