{{- $fullname := include "flink.fullname" . -}}
{{- $name := include "flink.name" . -}}
{{- $chart := include "flink.chart" . -}}
{{- $root := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-jobmanager-headless
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 8081
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
    role: jobmanager
