{{- $fullname := include "flink.fullname" . -}}
{{- $name := include "flink.name" . -}}
{{- $root := . }}
{{ if $root.Values.storage.create }}
{{ range .Values.nodes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullname }}-jobmanager-k8s{{ . }}
  labels:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
    node: k8s{{ . }}
    role: jobmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  local:
    path: /var/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s{{ . }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullname }}-taskmanager-k8s{{ . }}
  labels:
    app: {{ $name }}
    release: {{ $root.Release.Name }}
    node: k8s{{ . }}
    role: taskmanager
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  local:
    path: /var/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s{{ . }}
    {{ end }}
{{ end }}
