global:
  storageClass: hostpath-csi

zookeeper:
  image:
    pullPolicy: IfNotPresent
  replicaCount: 3
  heapSize: 512
  resources:
    limits:
     cpu: 500m
     memory: 700Mi
    requests:
     cpu: 100m
     memory: 700Mi
  # updateStrategy:
  #   type: OnDelete
  podAntiAffinityPreset: hard
  metrics:
    enabled: true
