# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry:
  repository: nextbreakpoint/zookeeper
  tag: 3.8.0
  pullPolicy: Always
  pullSecrets:

service:
  firstExternalClientPort: 32100
  firstExternalLeaderPort: 32130
  firstExternalPeerPort: 32120
  firstExternalMetricsPort: 32190

resources:
  limits:
   cpu: 100m
   memory: 300Mi
  requests:
   cpu: 100m
   memory: 300Mi

environment:
  jvmFlags: "-Xms256M -Xmx256M"

secrets:
  password:

nodes:
  - "1"
  - "2"
  - "3"

storage:
  create: false
